// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tones.Models;

#nullable disable

namespace Tones.Migrations
{
    [DbContext(typeof(ToneDbContext))]
    partial class ToneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Tones.Models.Tone", b =>
                {
                    b.Property<int>("ToneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ToneId");

                    b.ToTable("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
